services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - test-network
    command: sh -c "npm run test"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=gestao_user
      - POSTGRES_PASSWORD=gestao123
      - POSTGRES_DB=gestao_estoque_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gestao_user -d gestao_estoque_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
